from .colors import BaseColormaps, BaseColors, BasePalettes, get_color_mapping
from .figure import create_figure, label_axes, save_figure
from .plots import (
    PlotConfig,
    Plots,  # Kept here for backward compatibility, using Plots raises and alerts the user about the deprecation and how to upgrade.
    add_legend_to_axes,
    add_legend_to_axes_from_patches,
    add_lines,
    barplot,
    boxplot,
    histogram,
    label_plot,
    layered_plot,
    make_scatter_config,
    plot_pca,
    plot_pca_loadings,
    plot_pca_loadings_2d,
    rank_median_plot,
    scatter,
    scree_plot,
    violinplot,
    volcano,
)

__all__ = [
    "BaseColormaps",
    "BaseColors",
    "BasePalettes",
    "PlotConfig",
    "Plots",
    "add_legend_to_axes",
    "add_legend_to_axes_from_patches",
    "add_lines",
    "barplot",
    "boxplot",
    "create_figure",
    "get_color_mapping",
    "histogram",
    "label_axes",
    "label_plot",
    "layered_plot",
    "make_scatter_config",
    "plot_pca",
    "plot_pca_loadings",
    "plot_pca_loadings_2d",
    "rank_median_plot",
    "save_figure",
    "scatter",
    "scree_plot",
    "violinplot",
    "volcano",
]
